# Generated by Django 4.2.19 on 2025-10-24 01:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0004_alter_chat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('professionalism_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subject_knowledge_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clarity_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback_text', models.TextField(blank=True)),
                ('question_responses', models.JSONField(default=list)),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('total_responses_given', models.IntegerField(default=0)),
                ('interview_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='exports/pdfs/')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exportable_report', to='active_interview_app.chat')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
