# Generated by Django 4.2.19 on 2025-11-03 12:00
# INTENTIONAL CONFLICT - Testing migration sync workflow

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=500),  # Intentionally different change
        ),
    ]
