# Generated by Django 4.2.19 on 2025-10-26 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0002_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PER', 'Personality/Preliminary'), ('FSC', 'Final Screening'), ('GEN', 'General'), ('ISK', 'Industry Skills')], default='GEN', max_length=3),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('git_branch', models.CharField(db_index=True, help_text='Git branch where this request originated', max_length=255)),
                ('model_name', models.CharField(db_index=True, help_text="AI model used (e.g., 'gpt-4o', 'claude-sonnet-4-5-20250929')", max_length=100)),
                ('endpoint', models.CharField(help_text='API endpoint called', max_length=255)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of tokens in the prompt/input')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of tokens in the completion/output')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used (prompt + completion)')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['git_branch', 'model_name'], name='active_inte_git_bra_8847a2_idx'), models.Index(fields=['created_at', 'git_branch'], name='active_inte_created_b5e71c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MergeTokenStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_branch', models.CharField(db_index=True, help_text='Branch that was merged', max_length=255)),
                ('target_branch', models.CharField(default='main', help_text='Branch that received the merge', max_length=255)),
                ('merge_commit_sha', models.CharField(help_text='Git commit hash of the merge', max_length=40, unique=True)),
                ('pr_number', models.IntegerField(blank=True, help_text='Pull request number if applicable', null=True)),
                ('claude_prompt_tokens', models.IntegerField(default=0, help_text='Claude prompt tokens used by this branch')),
                ('claude_completion_tokens', models.IntegerField(default=0, help_text='Claude completion tokens used by this branch')),
                ('claude_total_tokens', models.IntegerField(default=0, help_text='Total Claude tokens used by this branch')),
                ('claude_request_count', models.IntegerField(default=0, help_text='Number of Claude API requests')),
                ('chatgpt_prompt_tokens', models.IntegerField(default=0, help_text='ChatGPT prompt tokens used by this branch')),
                ('chatgpt_completion_tokens', models.IntegerField(default=0, help_text='ChatGPT completion tokens used by this branch')),
                ('chatgpt_total_tokens', models.IntegerField(default=0, help_text='Total ChatGPT tokens used by this branch')),
                ('chatgpt_request_count', models.IntegerField(default=0, help_text='Number of ChatGPT API requests')),
                ('total_prompt_tokens', models.IntegerField(default=0, help_text='All prompt tokens (Claude + ChatGPT)')),
                ('total_completion_tokens', models.IntegerField(default=0, help_text='All completion tokens (Claude + ChatGPT)')),
                ('total_tokens', models.IntegerField(default=0, help_text='All tokens used by this branch')),
                ('request_count', models.IntegerField(default=0, help_text='Total number of API requests')),
                ('cumulative_claude_tokens', models.IntegerField(default=0, help_text='Running total of all Claude tokens across all merges')),
                ('cumulative_chatgpt_tokens', models.IntegerField(default=0, help_text='Running total of all ChatGPT tokens across all merges')),
                ('cumulative_total_tokens', models.IntegerField(default=0, help_text='Running total of ALL tokens across all merges')),
                ('cumulative_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Running total cost in USD across all merges', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or metadata')),
                ('merged_by', models.ForeignKey(blank=True, help_text='User who performed the merge', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merge Token Statistics',
                'verbose_name_plural': 'Merge Token Statistics',
                'ordering': ['-merge_date'],
                'indexes': [models.Index(fields=['source_branch'], name='active_inte_source__77e85a_idx'), models.Index(fields=['merge_date'], name='active_inte_merge_d_fda0ff_idx')],
            },
        ),
    ]
