# Generated by Django 4.2.19 on 2025-11-03 11:45
# SPLIT BRANCH - Creates a conflicting migration tree

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0002_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='difficulty',
            field=models.IntegerField(default=1),  # Changed default
        ),
    ]
