# Generated by Django 4.2.19 on 2025-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0003_alter_chat_type_tokenusage_mergetokenstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('FSC', 'Final Screening'), ('GEN', 'General'), ('ISK', 'Industry Skills'), ('PER', 'Personality/Preliminary')], default='GEN', max_length=3),
        ),
    ]
