# Generated by Django 4.2.19 on 2025-10-30 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0005_alter_chat_type_exportablereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedresume',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadedresume',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadedresume',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedresume',
            name='parsing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedresume',
            name='parsing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedresume',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chat',
            name='job_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='active_interview_app.uploadedjoblisting'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='key_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('FSC', 'Final Screening'), ('PER', 'Personality/Preliminary'), ('GEN', 'General'), ('ISK', 'Industry Skills')], default='GEN', max_length=3),
        ),
    ]
