# Generated by Django 4.2.19 on 2025-11-01 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0006_uploadedresume_education_uploadedresume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('ISK', 'Industry Skills'), ('GEN', 'General'), ('FSC', 'Final Screening'), ('PER', 'Personality/Preliminary')], default='GEN', max_length=3),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_provider', models.CharField(default='local', help_text='Authentication provider (e.g., local, google)', max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('interviewer', 'Interviewer'), ('candidate', 'Candidate')], default='candidate', help_text='User role for access control', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
