# Generated by Django 4.2.19 on 2025-11-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0007_alter_chat_type_userprofile_rolechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the interview template (e.g., "Technical Interview")', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the template purpose')),
                ('sections', models.JSONField(blank=True, default=list, help_text='List of sections in the template. Each section has: title, content, order, weight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='interview_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Template',
                'verbose_name_plural': 'Interview Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='active_inte_user_id_d49537_idx')],
            },
        ),
    ]
