# Generated by Django 4.2.19 on 2025-11-01 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0007_alter_chat_type_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('ISK', 'Industry Skills'), ('PER', 'Personality/Preliminary'), ('GEN', 'General'), ('FSC', 'Final Screening')], default='GEN', max_length=3),
        ),
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(help_text='Role being requested (typically "interviewer")', max_length=20)),
                ('current_role', models.CharField(help_text='Role at time of request', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='User explanation for role request')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='active_inte_status_dcee21_idx'), models.Index(fields=['user', '-created_at'], name='active_inte_user_id_c81fd5_idx')],
            },
        ),
    ]
