# Generated by Django 4.2.19 on 2025-11-03 12:30
# NONSENSE MIGRATION - out of order, should have been after 0007

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0009_testdummymodel'),  # Depends on future migration!
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='nonsense_field',
            field=models.CharField(max_length=50, default='test'),
        ),
    ]
