# Generated by Django 4.2.19 on 2025-11-15 09:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0007_alter_chat_type_userprofile_rolechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='active_interview_app.questionbank')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='active_interview_app.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the interview template (e.g., "Technical Interview")', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the template purpose')),
                ('sections', models.JSONField(blank=True, default=list, help_text='List of sections in the template. Each section has: title, content, order, weight')),
                ('use_auto_assembly', models.BooleanField(default=False, help_text='Enable automatic interview assembly from question banks')),
                ('question_count', models.IntegerField(default=5, help_text='Number of questions for auto-assembly', validators=[django.core.validators.MinValueValidator(1)])),
                ('easy_percentage', models.IntegerField(default=30, help_text='Percentage of easy questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medium_percentage', models.IntegerField(default=50, help_text='Percentage of medium questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hard_percentage', models.IntegerField(default=20, help_text='Percentage of hard questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_banks', models.ManyToManyField(blank=True, help_text='Question banks to use for auto-assembly', related_name='templates', to='active_interview_app.questionbank')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags to filter questions for auto-assembly', related_name='templates', to='active_interview_app.tag')),
                ('user', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='interview_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Template',
                'verbose_name_plural': 'Interview Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='active_inte_user_id_d49537_idx')],
            },
        ),
    ]
