# Generated by Django 4.2.19 on 2025-11-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0007_exportablereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PER', 'Personality/Preliminary'), ('ISK', 'Industry Skills'), ('GEN', 'General'), ('FSC', 'Final Screening')], default='GEN', max_length=3),
        ),
    ]
