# Generated by Django 4.2.19 on 2025-11-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0007_alter_chat_type_userprofile_rolechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test_field', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnotherTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dummy_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active_interview_app.testdummymodel')),
            ],
        ),
    ]
