# Generated by Django 4.2.19 on 2025-11-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0008_interviewtemplate'),
        ('active_interview_app', '0008_tag_questionbank_question_interviewtemplate'),
    ]

    operations = [
    ]
