# Generated by Django 4.2.19 on 2025-11-15 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0008_interviewtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='clarity_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='clarity_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='overall_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='professionalism_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='professionalism_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='subject_knowledge_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='subject_knowledge_weight',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='easy_percentage',
            field=models.IntegerField(default=30, help_text='Percentage of easy questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='hard_percentage',
            field=models.IntegerField(default=20, help_text='Percentage of hard questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='medium_percentage',
            field=models.IntegerField(default=50, help_text='Percentage of medium questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='question_count',
            field=models.IntegerField(default=5, help_text='Number of questions for auto-assembly', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='use_auto_assembly',
            field=models.BooleanField(default=False, help_text='Enable automatic interview assembly from question banks'),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='active_interview_app.questionbank')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='active_interview_app.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='question_banks',
            field=models.ManyToManyField(blank=True, help_text='Question banks to use for auto-assembly', related_name='templates', to='active_interview_app.questionbank'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags to filter questions for auto-assembly', related_name='templates', to='active_interview_app.tag'),
        ),
    ]
