# Generated by Django 4.2.19 on 2025-11-11 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0008_interviewtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymized_user_id', models.CharField(help_text='Anonymized identifier for audit purposes', max_length=255)),
                ('username', models.CharField(help_text='Username at time of deletion (for audit trail)', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Email at time of deletion (for audit trail)', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if deletion failed')),
                ('total_interviews_deleted', models.IntegerField(default=0, help_text='Number of interviews anonymized')),
                ('total_resumes_deleted', models.IntegerField(default=0, help_text='Number of resumes deleted')),
                ('total_job_listings_deleted', models.IntegerField(default=0, help_text='Number of job listings deleted')),
            ],
            options={
                'verbose_name': 'Deletion Request',
                'verbose_name_plural': 'Deletion Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='active_inte_status_05ac08_idx'), models.Index(fields=['requested_at'], name='active_inte_request_45bb21_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', help_text='Current status of the export request', max_length=20)),
                ('export_file', models.FileField(blank=True, help_text='ZIP file containing exported user data', null=True, upload_to='exports/user_data/')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Export download link expires after 7 days', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if export failed')),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the export file in bytes', null=True)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times the export has been downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('user', models.ForeignKey(help_text='User requesting data export', on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export Request',
                'verbose_name_plural': 'Data Export Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='active_inte_user_id_a390af_idx'), models.Index(fields=['status', '-requested_at'], name='active_inte_status_a593a6_idx')],
            },
        ),
    ]
