# Generated by Django 4.2.19 on 2025-11-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0008_interviewtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtemplate',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='List of sections in the template. Each section has: title, content, order'),
        ),
    ]
