# Generated by Django 4.2.19 on 2025-11-15 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0008_tag_questionbank_question_interviewtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportablereport',
            name='clarity_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='clarity_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='overall_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='professionalism_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='professionalism_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='subject_knowledge_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='subject_knowledge_weight',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
