# Generated by Django 4.2.19 on 2025-11-03 12:15
# WRONG NUMBER - should be 0008, testing migration workflow

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0007_alter_chat_type_userprofile_rolechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test_field', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
