# Generated by Django 4.2.19 on 2025-11-15 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0009_interviewtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportablereport',
            name='clarity_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='clarity_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='overall_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='professionalism_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='professionalism_weight',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='subject_knowledge_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportablereport',
            name='subject_knowledge_weight',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        # Use SeparateDatabaseAndState for fields that already exist from migration 0008
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='interviewtemplate',
                    name='easy_percentage',
                    field=models.IntegerField(default=30, help_text='Percentage of easy questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
                ),
                migrations.AddField(
                    model_name='interviewtemplate',
                    name='hard_percentage',
                    field=models.IntegerField(default=20, help_text='Percentage of hard questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
                ),
                migrations.AddField(
                    model_name='interviewtemplate',
                    name='medium_percentage',
                    field=models.IntegerField(default=50, help_text='Percentage of medium questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
                ),
                migrations.AddField(
                    model_name='interviewtemplate',
                    name='question_count',
                    field=models.IntegerField(default=5, help_text='Number of questions for auto-assembly', validators=[django.core.validators.MinValueValidator(1)]),
                ),
                migrations.AddField(
                    model_name='interviewtemplate',
                    name='tags',
                    field=models.ManyToManyField(blank=True, help_text='Tags to filter questions for auto-assembly', related_name='templates', to='active_interview_app.tag'),
                ),
            ],
            database_operations=[
                # No database operations - these fields already exist from migration 0008
            ],
        ),
        # Add new fields that don't exist in the database yet
        migrations.AddField(
            model_name='interviewtemplate',
            name='question_banks',
            field=models.ManyToManyField(blank=True, help_text='Question banks to use for auto-assembly', related_name='templates', to='active_interview_app.questionbank'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='use_auto_assembly',
            field=models.BooleanField(default=False, help_text='Enable automatic interview assembly from question banks'),
        ),
    ]
