# Generated by Django 4.2.19 on 2025-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0009_tag_exportablereport_clarity_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_dummy_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
