# Generated by Django 4.2.19 on 2025-11-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0009_chat_interview_type_invitedinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled time when interview should end', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Time when the interview session started', null=True),
        ),
    ]
