# Generated by Django 4.2.19 on 2025-11-03 12:20
# BAD DEPENDENCY - references wrong migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0015_nonexistent'),  # This doesn't exist!
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dummy_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active_interview_app.testdummymodel')),
            ],
        ),
    ]
