# Generated by Django 4.2.19 on 2025-11-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0010_deletionrequest_dataexportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='parsed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when job description was successfully parsed', null=True),
        ),
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='parsing_error',
            field=models.TextField(blank=True, help_text='Error message if parsing failed', null=True),
        ),
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='parsing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('error', 'Error')], default='pending', help_text='Status of AI parsing for this job listing', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='recommended_template',
            field=models.ForeignKey(blank=True, help_text='Auto-recommended interview template based on job requirements', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='active_interview_app.interviewtemplate'),
        ),
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills extracted from job description'),
        ),
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Structured requirements extracted from job description'),
        ),
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead/Principal'), ('executive', 'Executive')], help_text='Inferred seniority level from job description', max_length=50),
        ),
    ]
