# Generated by Django 4.2.19 on 2025-11-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0009_deletionrequest_dataexportrequest'),
        ('active_interview_app', '0010_merge_interviewtemplate_models'),
    ]

    operations = [
    ]
