# Generated by Django 4.2.19 on 2025-11-16
# Migration for Observability Models (Issues #14, #15)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0010_deletionrequest_dataexportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, help_text="Request path (e.g., '/api/chat/')", max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(db_index=True, help_text='HTTP response status code')),
                ('response_time_ms', models.FloatField(help_text='Response time in milliseconds')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of authenticated user (null for anonymous)', null=True)),
            ],
            options={
                'verbose_name': 'Request Metric',
                'verbose_name_plural': 'Request Metrics',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['endpoint', '-timestamp'], name='active_inte_endpoin_idx001'),
                    models.Index(fields=['status_code', '-timestamp'], name='active_inte_status_idx001'),
                    models.Index(fields=['-timestamp'], name='active_inte_timesta_idx001'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DailyMetricsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('client_errors', models.IntegerField(default=0)),
                ('server_errors', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('p50_response_time', models.FloatField(default=0.0)),
                ('p95_response_time', models.FloatField(default=0.0)),
                ('max_response_time', models.FloatField(default=0.0)),
                ('endpoint_stats', models.JSONField(default=dict, help_text='Per-endpoint statistics for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Metrics Summary',
                'verbose_name_plural': 'Daily Metrics Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCostDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('provider', models.CharField(db_index=True, help_text="Provider name (e.g., 'OpenAI', 'Anthropic')", max_length=100)),
                ('service', models.CharField(help_text="Service type (e.g., 'gpt-4o', 'claude-sonnet-4')", max_length=100)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, help_text='Total cost in USD', max_digits=10)),
                ('total_tokens', models.BigIntegerField(default=0, help_text='Total tokens used (if applicable)')),
                ('prompt_tokens', models.BigIntegerField(default=0, help_text='Prompt tokens used')),
                ('completion_tokens', models.BigIntegerField(default=0, help_text='Completion tokens used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Cost (Daily)',
                'verbose_name_plural': 'Provider Costs (Daily)',
                'ordering': ['-date', 'provider'],
                'unique_together': {('date', 'provider', 'service')},
                'indexes': [
                    models.Index(fields=['-date', 'provider'], name='active_inte_date_pr_idx001'),
                    models.Index(fields=['provider', '-date'], name='active_inte_provide_idx001'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('error_type', models.CharField(help_text='Exception class name', max_length=255)),
                ('error_message', models.TextField(help_text='Error message')),
                ('stack_trace', models.TextField(blank=True, help_text='Full stack trace')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('request_data', models.JSONField(default=dict, help_text='Request parameters and headers')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['-timestamp'], name='active_inte_timesta_idx002'),
                    models.Index(fields=['endpoint', '-timestamp'], name='active_inte_endpoin_idx002'),
                    models.Index(fields=['error_type', '-timestamp'], name='active_inte_error_t_idx001'),
                ],
            },
        ),
    ]
