# Generated by Django 4.2.19 on 2025-11-16
# Migration to change auto_now_add to default for testability

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0011_observability_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmetric',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
