# Generated by Django 4.2.19 on 2025-11-16 22:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0011_uploadedjoblisting_parsed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='interview_type',
            field=models.CharField(choices=[('PRACTICE', 'Practice Interview'), ('INVITED', 'Invited Interview')], default='PRACTICE', help_text='Whether this is a practice or invited interview', max_length=10),
        ),
        migrations.AddField(
            model_name='chat',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled time when interview should end', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Time when the interview session started', null=True),
        ),
        migrations.CreateModel(
            name='InvitedInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for secure join links', primary_key=True, serialize=False)),
                ('candidate_email', models.EmailField(help_text='Email address of the candidate', max_length=254)),
                ('scheduled_time', models.DateTimeField(help_text='When the interview can start')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration window for completing the interview (15-240 minutes)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('expired', 'Expired')], default='pending', help_text='Current status of the invitation', max_length=20)),
                ('interviewer_review_status', models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Review Complete')], default='pending', help_text='Whether interviewer has reviewed the completed interview', max_length=20)),
                ('interviewer_feedback', models.TextField(blank=True, help_text='Feedback provided by the interviewer after review')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the interviewer marked this as reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, help_text='When the invitation email was sent', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the candidate completed the interview', null=True)),
                ('chat', models.OneToOneField(blank=True, help_text='The actual interview session (Chat)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='active_interview_app.chat')),
                ('interviewer', models.ForeignKey(help_text='Interviewer who sent this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Interview template structure for this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='active_interview_app.interviewtemplate')),
            ],
            options={
                'verbose_name': 'Invited Interview',
                'verbose_name_plural': 'Invited Interviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['interviewer', '-created_at'], name='active_inte_intervi_3ac9d2_idx'), models.Index(fields=['candidate_email'], name='active_inte_candida_29dd50_idx'), models.Index(fields=['status'], name='active_inte_status_04d265_idx'), models.Index(fields=['scheduled_time'], name='active_inte_schedul_68eaf1_idx')],
            },
        ),
    ]
