# Generated by Django 4.2.19 on 2025-11-16
# Migration to change TokenUsage created_at from auto_now_add to default

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0012_alter_requestmetric_timestamp_errorlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
