# Generated by Django 4.2.19 on 2025-11-30 07:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0013_dailymetricssummary_alter_tokenusage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', help_text='API provider (e.g., OpenAI, Anthropic)', max_length=50)),
                ('model_tier', models.CharField(choices=[('premium', 'Premium (GPT-4o, Claude Opus)'), ('standard', 'Standard (GPT-4-turbo, Claude Sonnet)'), ('fallback', 'Fallback (GPT-3.5-turbo, Budget models)')], default='premium', help_text='Model tier for cost control (premium/standard/fallback)', max_length=20)),
                ('key_name', models.CharField(help_text='Friendly name for this key (e.g., "Production Key 1")', max_length=255)),
                ('encrypted_key', models.BinaryField(help_text='Encrypted API key value')),
                ('key_prefix', models.CharField(help_text='First few characters of key for identification (e.g., "sk-proj-abc...")', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='pending', help_text='Current status of this key', max_length=20)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this key has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used for an API call', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this key was activated', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When this key was deactivated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this key')),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin who added this key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Key Pool',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySpendingCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_amount_usd', models.DecimalField(decimal_places=2, help_text='Maximum allowed monthly spending in USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cap is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who set this cap', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Spending Cap',
                'verbose_name_plural': 'Monthly Spending Caps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total spending for this month in USD', max_digits=10)),
                ('llm_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='LLM (GPT-4o, Claude) costs in USD', max_digits=10)),
                ('tts_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Text-to-Speech costs in USD', max_digits=10)),
                ('other_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Other API costs in USD', max_digits=10)),
                ('premium_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Premium tier (GPT-4o, Claude Opus) costs in USD', max_digits=10)),
                ('standard_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard tier (GPT-4-turbo, Claude Sonnet) costs in USD', max_digits=10)),
                ('fallback_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Fallback tier (GPT-3.5-turbo, budget models) costs in USD', max_digits=10)),
                ('total_requests', models.IntegerField(default=0, help_text='Total number of API requests this month')),
                ('llm_requests', models.IntegerField(default=0, help_text='Number of LLM requests this month')),
                ('tts_requests', models.IntegerField(default=0, help_text='Number of TTS requests this month')),
                ('premium_requests', models.IntegerField(default=0, help_text='Number of premium tier requests this month')),
                ('standard_requests', models.IntegerField(default=0, help_text='Number of standard tier requests this month')),
                ('fallback_requests', models.IntegerField(default=0, help_text='Number of fallback tier requests this month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_from_token_usage', models.DateTimeField(blank=True, help_text='Last time spending was calculated from TokenUsage records', null=True)),
            ],
            options={
                'verbose_name': 'Monthly Spending',
                'verbose_name_plural': 'Monthly Spending Records',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['-year', '-month'], name='active_inte_year_cd2e9f_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='KeyRotationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', help_text='API provider this schedule applies to', max_length=50)),
                ('model_tier', models.CharField(choices=[('premium', 'Premium (GPT-4o, Claude Opus)'), ('standard', 'Standard (GPT-4-turbo, Claude Sonnet)'), ('fallback', 'Fallback (GPT-3.5-turbo, Budget models)')], default='premium', help_text='Model tier for this rotation schedule', max_length=20)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether automatic rotation is enabled')),
                ('rotation_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', help_text='How often to rotate keys', max_length=20)),
                ('last_rotation_at', models.DateTimeField(blank=True, help_text='When the last rotation occurred', null=True)),
                ('next_rotation_at', models.DateTimeField(blank=True, help_text='When the next rotation is scheduled', null=True)),
                ('notify_on_rotation', models.BooleanField(default=True, help_text='Send notification when rotation occurs')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address for rotation notifications', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who configured this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Rotation Schedule',
                'verbose_name_plural': 'Key Rotation Schedules',
                'ordering': ['provider', 'model_tier'],
                'unique_together': {('provider', 'model_tier')},
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], help_text='API provider', max_length=50)),
                ('old_key_masked', models.CharField(help_text='Masked old key (for audit even if key is deleted)', max_length=50)),
                ('new_key_masked', models.CharField(help_text='Masked new key (for audit even if key is deleted)', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], help_text='Result of rotation attempt', max_length=20)),
                ('rotation_type', models.CharField(default='scheduled', help_text='Type of rotation (scheduled, manual, forced)', max_length=20)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if rotation failed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this rotation')),
                ('new_key', models.ForeignKey(blank=True, help_text='Key that was activated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs_as_new_key', to='active_interview_app.apikeypool')),
                ('old_key', models.ForeignKey(blank=True, help_text='Key that was deactivated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs_as_old_key', to='active_interview_app.apikeypool')),
                ('rotated_by', models.ForeignKey(blank=True, help_text='Admin who initiated rotation (null for automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Rotation Log',
                'verbose_name_plural': 'Key Rotation Logs',
                'ordering': ['-rotated_at'],
                'indexes': [models.Index(fields=['provider', '-rotated_at'], name='active_inte_provide_71ffe6_idx'), models.Index(fields=['status', '-rotated_at'], name='active_inte_status_894118_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apikeypool',
            index=models.Index(fields=['provider', 'model_tier', 'status'], name='active_inte_provide_58999d_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeypool',
            index=models.Index(fields=['provider', 'status'], name='active_inte_provide_ad07c6_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeypool',
            index=models.Index(fields=['status', '-added_at'], name='active_inte_status_38716f_idx'),
        ),
    ]
