# Generated by Django 4.2.19 on 2025-11-29 23:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0014_apikeypool_monthlyspendingcap_monthlyspending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyspending',
            name='fallback_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Fallback tier (GPT-3.5-turbo, budget models) costs in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyspending',
            name='fallback_requests',
            field=models.IntegerField(default=0, help_text='Number of fallback tier requests this month'),
        ),
        migrations.AddField(
            model_name='monthlyspending',
            name='premium_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Premium tier (GPT-4o, Claude Opus) costs in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyspending',
            name='premium_requests',
            field=models.IntegerField(default=0, help_text='Number of premium tier requests this month'),
        ),
        migrations.AddField(
            model_name='monthlyspending',
            name='standard_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard tier (GPT-4-turbo, Claude Sonnet) costs in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyspending',
            name='standard_requests',
            field=models.IntegerField(default=0, help_text='Number of standard tier requests this month'),
        ),
    ]
