# Generated by Django 5.2.8 on 2025-11-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0014_biasanalysisresult_biastermlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasanalysisresult',
            name='object_id',
            field=models.CharField(help_text='ID of the specific object (supports both integer IDs and UUIDs)', max_length=255),
        ),
    ]
