# Generated by Django 4.2.19 on 2025-12-01 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0014_apikeypool_monthlyspendingcap_monthlyspending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResponseLatency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response_time_ms', models.FloatField(help_text='Total response time in milliseconds')),
                ('ai_processing_time_ms', models.FloatField(blank=True, help_text='OpenAI API call duration in milliseconds', null=True)),
                ('question_number', models.IntegerField(help_text='Question sequence number in the interview')),
                ('interview_type', models.CharField(help_text='Interview type (PRACTICE or INVITED)', max_length=20)),
                ('exceeded_threshold', models.BooleanField(db_index=True, default=False, help_text='True if response time exceeded latency budget (2000ms)')),
                ('threshold_ms', models.IntegerField(default=2000, help_text='Latency threshold that was configured at time of request')),
                ('chat', models.ForeignKey(help_text='Interview chat session', on_delete=django.db.models.deletion.CASCADE, related_name='response_latencies', to='active_interview_app.chat')),
                ('user', models.ForeignKey(blank=True, help_text='User who received the response', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Response Latency',
                'verbose_name_plural': 'Interview Response Latencies',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['chat', '-timestamp'], name='active_inte_chat_id_4ae95e_idx'), models.Index(fields=['user', '-timestamp'], name='active_inte_user_id_771555_idx'), models.Index(fields=['exceeded_threshold', '-timestamp'], name='active_inte_exceede_b59eb3_idx'), models.Index(fields=['interview_type', '-timestamp'], name='active_inte_intervi_287609_idx'), models.Index(fields=['-timestamp'], name='active_inte_timesta_3e1b15_idx')],
            },
        ),
    ]
