# Generated by Django 4.2.19 on 2025-12-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0015_ratelimitviolation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratelimitviolation',
            new_name='active_inte_timesta_d76afb_idx',
            old_name='active_inte_timesta_e8b7c9_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitviolation',
            new_name='active_inte_timesta_ba5243_idx',
            old_name='active_inte_timesta_a1f5d2_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitviolation',
            new_name='active_inte_endpoin_f12daa_idx',
            old_name='active_inte_endpoin_c4e3f1_idx',
        ),
    ]
