# Generated by Django 4.2.19 on 2025-12-04 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0015_chat_finalized_at_chat_is_finalized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('ADMIN_CREATE', 'Admin Created Object'), ('ADMIN_UPDATE', 'Admin Updated Object'), ('ADMIN_DELETE', 'Admin Deleted Object')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='Type of resource affected (e.g., "User", "Chat")', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=255)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/client user agent string', max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional action-specific metadata')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'user'], name='active_inte_timesta_6c04e9_idx'), models.Index(fields=['action_type', '-timestamp'], name='active_inte_action__13fd89_idx'), models.Index(fields=['ip_address', '-timestamp'], name='active_inte_ip_addr_de01d4_idx')],
            },
        ),
    ]
