# Generated by Django 5.2.8 on 2025-11-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0015_alter_biasanalysisresult_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasanalysisresult',
            name='flagged_terms',
            field=models.JSONField(blank=True, default=list, help_text='List of detected bias terms with details. Structure: [{"term": str, "category": str, "severity": int, "positions": [int], "suggestions": [str]}, ...]'),
        ),
    ]
