# Generated by Django 4.2.19 on 2025-12-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0016_remove_chat_finalized_at_remove_chat_is_finalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the interview was finalized', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Whether the interview has been finalized and report generated'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_question_at',
            field=models.DateTimeField(blank=True, help_text='When the last question was asked (for graceful ending calculation)', null=True),
        ),
        migrations.AddField(
            model_name='invitedinterview',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last time candidate interacted with interview (for abandonment detection)', null=True),
        ),
    ]
