# Generated by Django 5.2.8 on 2025-12-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0016_alter_biasanalysisresult_flagged_terms'),
        ('active_interview_app', '0018_auditlog'),
    ]

    operations = [
    ]
