# Generated by Django 4.2.19 on 2025-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0018_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('ADMIN_CREATE', 'Admin Created Object'), ('ADMIN_UPDATE', 'Admin Updated Object'), ('ADMIN_DELETE', 'Admin Deleted Object'), ('INTERVIEW_FINALIZED', 'Interview Finalized'), ('REPORT_EXPORTED', 'Report Exported'), ('RESUME_DELETED', 'Resume Deleted'), ('ROLE_CHANGED', 'User Role Changed'), ('RATE_LIMIT_VIOLATION', 'Rate Limit Violation')], db_index=True, help_text='Type of action performed', max_length=50),
        ),
    ]
