name: AI Code Review

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  aireview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run AI Code Review
        run: |
          python scripts/ai-review.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
