name: AI Code Review

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  aireview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install openai
      
      - name: Run AI Code Review
        run: |
          python scripts/ai-review.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
