name: Continuous Deployment Workflow
on:
  push:
    branches:
      - prod
      - feature/cd

jobs:
  deploy:
    name: "Deploy to Digital Ocean"
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/prod' 
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/do.key
          chmod 600 ~/.ssh/do.key
          cat >>~/.ssh/config <<END
          Host do
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/do.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DO_SSH_USER }}
          SSH_KEY: ${{ secrets.DO_SSH_KEY }}
          SSH_HOST: ${{ secrets.DO_SSH_HOST }}

      - name: Test connection
        run: ssh -i ~/.ssh/do.key -o StrictHostKeyChecking=no do 'echo "Connected"'

      - name: Stop the server
        run: ssh do 'cd ~/Group-7-Spring-2025; docker-compose down'

      - name: Check out the source
        run: ssh do 'cd ~/Group-7-Spring-2025 && git fetch && git reset --hard origin/prod'

      - name: Start the server
        if: ${{ always() }}
        run: ssh do 'cd ~/Group-7-Spring-2025; docker-compose up -d --build'

