name: Continuous Deployment

on:
  push:
    branches:
      - prod
      - main  # Deploy from main branch to Railway
    paths:
      - 'active_interview_backend/**'
      - 'railway.json'
      - '.github/workflows/CD.yml'
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    # Only run if tests pass
    needs: []  # Remove this line if you want to run independently

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway
      id: deploy
      continue-on-error: true
      run: railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Deployment Summary
      if: always()
      run: |
        {
          echo '# Railway Deployment'
          echo ''
          echo '## Status'
          if [ "${{ steps.deploy.outcome }}" == "success" ]; then
            echo '✅ Deployment successful'
          else
            echo '❌ Deployment failed'
          fi
          echo ''
          echo '## Details'
          echo "- Branch: ${{ github.ref_name }}"
          echo "- Commit: ${{ github.sha }}"
          echo "- Triggered by: ${{ github.actor }}"
          echo "- Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        } >> $GITHUB_STEP_SUMMARY
